{
  "contest": 271,
  "handle": "debo",
  "risk": "2",
  "title": "Denial of Service with failed call Dos",
  "issueId": 105,
  "issueUrl": "https://github.com/code-423n4/2023-08-pooltogether-findings/issues/105"
}